import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import data from './airport-data.json';
import { createAirportSuppression } from './airport-suppression.js';
import { aircraftParts } from './aircraft-model.js';

export const AIRPORT_DATA = data;
const colours={pavement:0x565b5d,apron:0x95988f,grass:0x71836a,white:0xe4e5dd,yellow:0xc9b896,stone:0xc3bba6,roof:0x6b7779,glass:0x76979f,steel:0xcbd3d2,dark:0x38454a,tail:0x526c80};
const inside=(x,z,ring)=>{let hit=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++)if((ring[i][1]>z)!==(ring[j][1]>z)&&x<(ring[j][0]-ring[i][0])*(z-ring[i][1])/(ring[j][1]-ring[i][1])+ring[i][0])hit=!hit;return hit;};
const clean=ring=>ring.filter((p,i)=>!i||p[0]!==ring[i-1][0]||p[1]!==ring[i-1][1]).filter((p,i,a)=>!i||i!==a.length-1||p[0]!==a[0][0]||p[1]!==a[0][1]);
/** Only mapped replacement footprints, never an airport radius. The optional footprint
 * admits coincident old-source polygons whose centroid falls in an OSM courtyard. */
export const isAirportBuilding = createAirportSuppression(data);

function shape(points,height){const s=new THREE.Shape(points.map(([x,z])=>new THREE.Vector2(x,-z)));const g=new THREE.ExtrudeGeometry(s,{depth:height,bevelEnabled:false,steps:1});g.rotateX(-Math.PI/2);return g;}
function box(w,h,d,x=0,y=0,z=0,yaw=0){const g=new THREE.BoxGeometry(Math.max(.05,w),Math.max(.05,h),Math.max(.05,d));g.rotateY(yaw);g.translate(x,y,z);return g;}
function beam(a,b,r=.5){const d=new THREE.Vector3().subVectors(b,a),g=new THREE.CylinderGeometry(r,r,d.length(),6);g.applyQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize()));g.translate(...a.clone().add(b).multiplyScalar(.5).toArray());return g;}
function bounds(ring){let edge=0,angle=0;for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length],d=Math.hypot(b[0]-a[0],b[1]-a[1]);if(d>edge){edge=d;angle=Math.atan2(-(b[1]-a[1]),b[0]-a[0]);}}const c=Math.cos(angle),s=Math.sin(angle),local=ring.map(([x,z])=>[c*x-s*z,s*x+c*z]);const xs=local.map(p=>p[0]),zs=local.map(p=>p[1]),u=(Math.min(...xs)+Math.max(...xs))/2,v=(Math.min(...zs)+Math.max(...zs))/2;return {x:c*u+s*v,z:-s*u+c*v,w:Math.max(...xs)-Math.min(...xs),d:Math.max(...zs)-Math.min(...zs),yaw:angle};}

/** Static airports in the scene's canonical BNG X/Z coordinate system. getSurfaceY
 * must return canonical pre-master world Y, already carrying terrain VE. Master
 * height belongs on the common world parent. No update/tick is needed. */
export function createAirports({getSurfaceY,VE=5,heightScale=1}={}) {
 if(typeof getSurfaceY!=='function')throw new Error('Airports require getSurfaceY');
 for(const site of data.airports)if(!Number.isFinite(getSurfaceY({x:site.centre[0],z:site.centre[1]})))throw new Error(`No airport terrain at ${site.id}`);
 const root=new THREE.Group();root.name='airports';const meshes=[],surfaces=[],mats={};
 for(const [key,color]of Object.entries(colours))mats[key]=new THREE.MeshStandardMaterial({color,roughness:key==='glass'?.4:.85,metalness:key==='steel'?.3:0,fog:true});
 const sample=(x,z)=>{const y=getSurfaceY({x,z});if(!Number.isFinite(y))throw new Error(`No airport terrain at ${x},${z}`);return y;};
 const stats={airports:data.airports.length,buildings:0,aircraft:0,queued:0,runways:0,drawCalls:0};
 for(const site of data.airports){const group=new THREE.Group();group.name=`airport-${site.id}`;group.userData.airport=site.id;root.add(group);const batches=new Map(),ground=new Map(),aircraft=[];let feature=null;const features=new Map();
 const add=(g,mat,base=0,anchor=null)=>{if(!g.index){}else{const old=g;g=g.toNonIndexed();old.dispose();}g.deleteAttribute('uv');const n=g.attributes.position.count;g.setAttribute('airportBase',new THREE.BufferAttribute(new Float32Array(n).fill(base),1));g.setAttribute('airportLift',new THREE.BufferAttribute(new Float32Array(n).fill(anchor?base-sample(...anchor):0),1));if(anchor){g.setAttribute('airportAnchor',new THREE.BufferAttribute(new Float32Array(Array.from({length:n},()=>anchor).flat()),2));}else g.setAttribute('airportAnchor',new THREE.BufferAttribute(new Float32Array(n*2),2));if(!batches.has(mat))batches.set(mat,[]);const start=batches.get(mat).reduce((n,p)=>n+p.attributes.position.count,0);if(feature){if(!features.has(mat))features.set(mat,[]);features.get(mat).push({...feature,start,end:start+n});}batches.get(mat).push(g);};
 const groundTriangle=(a,b,c,mat,lift=0.7)=>{if(!ground.has(mat))ground.set(mat,[]);const out=ground.get(mat);const split=(a,b,c,depth)=>{const ds=[Math.hypot(a[0]-b[0],a[1]-b[1]),Math.hypot(b[0]-c[0],b[1]-c[1]),Math.hypot(c[0]-a[0],c[1]-a[1])],i=ds.indexOf(Math.max(...ds));if(ds[i]>30&&depth<12){const p=[a,b,c],u=p[i],v=p[(i+1)%3],w=p[(i+2)%3],m=[(u[0]+v[0])/2,(u[1]+v[1])/2];split(u,m,w,depth+1);split(m,v,w,depth+1);}else for(const p of [a,b,c])out.push(p[0],sample(...p)+lift,p[1]);};split(a,b,c,0);};
 const strip=(a,b,width,mat,lift=.8)=>{const len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len<.05)return;const nx=-(b[1]-a[1])/len*width/2,nz=(b[0]-a[0])/len*width/2;const p=[[a[0]+nx,a[1]+nz],[b[0]+nx,b[1]+nz],[b[0]-nx,b[1]-nz],[a[0]-nx,a[1]-nz]];groundTriangle(p[0],p[1],p[2],mat,lift);groundTriangle(p[0],p[2],p[3],mat,lift);};
 for(const apron of site.aprons){const ring=clean(apron.points);if(ring.length<3)continue;for(const tri of THREE.ShapeUtils.triangulateShape(ring.map(p=>new THREE.Vector2(...p)),[]))groundTriangle(...tri.map(i=>ring[i]),'apron',.5);}
 for(const taxi of site.taxiways)for(let i=1;i<taxi.points.length;i++){strip(taxi.points[i-1],taxi.points[i],taxi.width,'pavement');strip(taxi.points[i-1],taxi.points[i],.65,'yellow',1.05);}
 for(const runway of site.runways){stats.runways++;for(let i=1;i<runway.points.length;i++)strip(runway.points[i-1],runway.points[i],runway.width,runway.surface==='grass'?'grass':'pavement',1.15);for(const insert of runway.pavedInserts||[]){for(let i=1;i<insert.points.length;i++)strip(insert.points[i-1],insert.points[i],insert.width,'pavement',1.25);const a=insert.points[0],b=insert.points.at(-1),length=Math.hypot(b[0]-a[0],b[1]-a[1]);for(let d=25;d<length-25;d+=60){const point=t=>[a[0]+(b[0]-a[0])*t/length,a[1]+(b[1]-a[1])*t/length];strip(point(d),point(Math.min(d+25,length-25)),1.2,'white',1.4);}}if(runway.surface==='grass')continue;const a=runway.points[0],b=runway.points.at(-1),len=Math.hypot(b[0]-a[0],b[1]-a[1]),dx=(b[0]-a[0])/len,dz=(b[1]-a[1])/len;const p=(t,side=0)=>[a[0]+dx*t-dz*side,a[1]+dz*t+dx*side];for(let d=100;d<len-90;d+=60)strip(p(d),p(Math.min(d+30,len-90)),1.8,'white',1.4);for(const sign of [-1,1])strip(p(0,sign*(runway.width/2-1.5)),p(len,sign*(runway.width/2-1.5)),.8,'white',1.4);for(const end of [0,1])for(let i=-3;i<=3;i++){if(!i)continue;const d=end?len-55:20;strip(p(d,i*4.3),p(d+30,i*4.3),2.1,'white',1.4);}}
 for(const b of site.buildings){feature={name:b.name||`${site.name} ${b.kind}`,kind:b.kind,osm:b.osm};if(site.id==='heathrow'&&b.kind==='tower')feature.heightM=87;if(site.id==='london-city'&&/Digital/.test(b.name))feature.heightM=50;stats.buildings++;const ring=clean(b.points),bd=ring.length>=3?bounds(ring):{x:ring[0][0],z:ring[0][1],w:12,d:12,yaw:0};const anchor=[bd.x,bd.z],base=sample(...anchor)+.5,h=b.height;const addLocal=(g,mat)=>{g.rotateY(bd.yaw);g.translate(bd.x,base,bd.z);add(g,mat,base,anchor);};
 if(b.kind==='tower'){const digital=/Digital/.test(b.name),shaft=new THREE.CylinderGeometry(digital?1.1:3,digital?1.7:4,h-7,10);shaft.translate(0,(h-7)/2,0);addLocal(shaft,'steel');addLocal(box(digital?8:17,4,digital?8:15,0,h-5),digital?'steel':'glass');addLocal(box(digital?9:19,1.2,digital?9:17,0,h-2.4),'roof');addLocal(box(.7,1.8,.7,0,h-.9),'steel');if(site.id==='heathrow'){for(let a=0;a<3;a++){const t=a*Math.PI*2/3;addLocal(beam(new THREE.Vector3(Math.cos(t)*24,0,Math.sin(t)*24),new THREE.Vector3(0,h-13,0),.3),'steel');}}continue;}
 const local=ring.map(([x,z])=>[x-bd.x,z-bd.z]);const body=shape(local,h*.82);body.translate(bd.x,base,bd.z);add(body,b.kind==='terminal'?'glass':'stone',base,anchor);const roof=shape(local,Math.max(.5,h*.1));roof.translate(bd.x,base+h*.82,bd.z);add(roof,'roof',base,anchor);
 // Roof and façade details follow mapped principal bearing, retaining original polygon bodies.
 const w=bd.w,d=bd.d;const t5=site.id==='heathrow'&&/Terminal 5$/.test(b.name),t2=site.id==='heathrow'&&/Terminal 2A/.test(b.name);
 if(t5||t2){const across=Math.min(w,d),along=Math.max(w,d),swap=d>w;for(let i=0;i<16;i++){const q0=-across/2+across*i/16,q1=-across/2+across*(i+1)/16,mid=(q0+q1)/2,roofY=h*.84+Math.cos(mid/across*Math.PI)*h*.16;const geo=box(swap?q1-q0:along,1.1,swap?along:q1-q0,swap?mid:0,roofY,swap?0:mid);addLocal(geo,'steel');}for(let j=-along/2+12;j<along/2;j+=24){const a=new THREE.Vector3(swap?-across/2:j,h*.83,swap?j:-across/2),c=new THREE.Vector3(swap?across/2:j,h*.83,swap?j:across/2);addLocal(beam(a,c,.7),'roof');}}
 for(let i=0;i<ring.length;i++){const a=ring[i],c=ring[(i+1)%ring.length],len=Math.hypot(c[0]-a[0],c[1]-a[1]);if(len<8)continue;const yaw=Math.atan2(-(c[1]-a[1]),c[0]-a[0]);for(let level=1;level<=Math.min(4,Math.floor(h/5));level++){const g=box(len,.6,1.1,(a[0]+c[0])/2,base+level*h/5,(a[1]+c[1])/2,yaw);add(g,'steel',base,anchor);}if(b.kind==='hangar'){const g=box(len*.76,h*.56,1.2,(a[0]+c[0])/2,base+h*.29,(a[1]+c[1])/2,yaw);add(g,'dark',base,anchor);}else if(b.kind==='terminal')for(let t=6;t<len;t+=12){const x=a[0]+(c[0]-a[0])*t/len,z=a[1]+(c[1]-a[1])*t/len;add(box(.7,h*.82,.7,x,base+h*.41,z),'steel',base,anchor);}}
 }
 const clear=(x,z,r)=>!site.buildings.some(b=>b.points.length>=3&&(inside(x,z,b.points)||b.points.some(p=>Math.hypot(p[0]-x,p[1]-z)<r)))&&!aircraft.some(a=>Math.hypot(a.x-x,a.z-z)<(a.length+r)*.55);
 const plane=(x,z,yaw,length,state,source)=>{feature={name:`${site.name} ${state} aircraft`,kind:'aircraft',source};const glider=site.kind==='gliding',width=length*(glider?2.25:length>30?.91:1.1),base=sample(x,z)+1.5,scale=length/60;const addPlane=(g,mat)=>{g.scale(scale,scale,scale);g.rotateY(yaw);g.translate(x,base,z);add(g,mat,base,[x,z]);};for(const [g,mat] of aircraftParts(length,{glider}))addPlane(g,mat);if(glider){
 aircraft.push({x,z,yaw,length,width,state,source,baseY:base,model:'glider',engines:0});stats.aircraft++;return;
 }aircraft.push({x,z,yaw,length,width,state,source,baseY:base});stats.aircraft++;if(state==='queued')stats.queued++;};
 const desired=site.kind==='gliding'?8:site.id==='heathrow'?58:site.kind==='passenger'?32:['business','military/civil'].includes(site.kind)?23:10;
 for(let i=0;i<site.stands.length;i+=(site.id==='heathrow'?3:1)){const st=site.stands[i],a=st.points[0],b=st.points.at(-1),dist=Math.hypot(b[0]-a[0],b[1]-a[1]);if(dist<8)continue;const len=site.id==='heathrow'?(i%2?60:43):desired,dx=(b[0]-a[0])/dist,dz=(b[1]-a[1])/dist,x=b[0]-dx*len*.35,z=b[1]-dz*len*.35;if(clear(x,z,len*.4))plane(x,z,Math.atan2(-dx,-dz),len,'parked',st.osm);}
 if(!site.stands.length){let count=0;const r=site.runways[0],a=r?.points[0],b=r?.points.at(-1),yaw=a?Math.atan2(a[0]-b[0],a[1]-b[1]):0;for(const apron of site.aprons){const bb=bounds(clean(apron.points));for(let x=bb.x-bb.w/2+desired;x<bb.x+bb.w/2&&count<8;x+=desired*1.8)for(let z=bb.z-bb.d/2+desired;z<bb.z+bb.d/2&&count<8;z+=desired*1.8)if(inside(x,z,apron.points)&&clear(x,z,desired)){plane(x,z,yaw,desired,'parked',apron.osm);count++;}}}
 if(site.id==='damyns-hall'&&!aircraft.length){const campus=site.buildings.map(b=>bounds(clean(b.points))),cx=campus.reduce((n,b)=>n+b.x,0)/campus.length,cz=campus.reduce((n,b)=>n+b.z,0)/campus.length;
 const runwayClear=(x,z)=>site.runways.every(r=>r.points.slice(1).every((b,i)=>{const a=r.points[i],dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz)));return Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz)>r.width/2+20;}));
 for(let z=cz+30;z<cz+140&&aircraft.length<5;z+=25)for(let x=cx-90;x<cx+90&&aircraft.length<5;x+=25)if(inside(x,z,site.boundary)&&clear(x,z,15)&&runwayClear(x,z))plane(x,z,0,9,'parked','Authored grass parking beside mapped campus way/170275687 and way/170275689');}
 // Authored stationary departure queue on a mapped taxiway, outside the runway.
 if(site.id==='heathrow'){const runway=site.runways.find(r=>r.name==='09R/27L'),end=runway?.points.reduce((a,b)=>a[0]>b[0]?a:b);if(end){const candidates=site.taxiways.filter(t=>/Taxiway S$/.test(t.name)).flatMap(t=>t.points.slice(1).map((b,i)=>({a:t.points[i],b,osm:t.osm}))).filter(s=>Math.hypot(s.b[0]-s.a[0],s.b[1]-s.a[1])>60&&Math.hypot((s.a[0]+s.b[0])/2-end[0],(s.a[1]+s.b[1])/2-end[1])<1100).sort((a,b)=>(b.a[0]+b.b[0])-(a.a[0]+a.b[0]));let queued=0;for(const s of candidates){const a=s.a[0]<s.b[0]?s.a:s.b,b=s.a[0]<s.b[0]?s.b:s.a,x=(a[0]+b[0])/2,z=(a[1]+b[1])/2;if(clear(x,z,28)){plane(x,z,Math.atan2(a[0]-b[0],a[1]-b[1]),43,'queued',s.osm);if(++queued===3)break;}}}}
 group.userData.aircraft=aircraft;group.userData.runways=site.runways;
 for(const [mat,positions]of ground){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.computeVertexNormals();const mesh=new THREE.Mesh(g,mats[mat]);mesh.name=`airport-surface-${site.id}-${mat}`;mesh.material.side=THREE.DoubleSide;mesh.userData={type:'airport',airportId:site.id,name:site.name,part:'surface'};group.add(mesh);surfaces.push(mesh);}
 for(const [mat,parts]of batches){const g=mergeGeometries(parts,false);for(const p of parts)p.dispose();const mesh=new THREE.Mesh(g,mats[mat]);mesh.name=`airport-architecture-${site.id}-${mat}`;mesh.userData={type:'airport',airportId:site.id,name:site.name,part:'architecture',features:features.get(mat)||[]};g.userData.original=new Float32Array(g.attributes.position.array);group.add(mesh);meshes.push(mesh);}
 }
 let current=heightScale;
 root.userData.setHeightScale=value=>{if(!Number.isFinite(value)||value<=0)throw new Error('Airport height scale must be positive');current=value;for(const m of meshes){const g=m.geometry,p=g.attributes.position,base=g.attributes.airportBase,original=g.userData.original;for(let i=0;i<p.count;i++)p.array[i*3+1]=base.array[i]+(original[i*3+1]-base.array[i])*VE*value;p.needsUpdate=true;g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();}};
 root.userData.refreshTerrain=()=>{for(const m of meshes){const g=m.geometry,anchor=g.attributes.airportAnchor,base=g.attributes.airportBase,original=g.userData.original;for(let i=0;i<base.count;i++){const newBase=sample(anchor.getX(i),anchor.getY(i))+g.attributes.airportLift.getX(i),delta=newBase-base.array[i];original[i*3+1]+=delta;base.array[i]=newBase;}}for(const m of surfaces){const p=m.geometry.attributes.position;const lifts=m.geometry.userData.lifts;if(!lifts)continue;for(let i=0;i<p.count;i++)p.array[i*3+1]=sample(p.getX(i),p.getZ(i))+lifts[i];p.needsUpdate=true;m.geometry.computeBoundingSphere();}root.userData.setHeightScale(current);};
 for(const m of surfaces){const p=m.geometry.attributes.position;m.geometry.userData.lifts=Float32Array.from({length:p.count},(_,i)=>p.getY(i)-sample(p.getX(i),p.getZ(i)));}
 root.userData.setHeightScale(heightScale);stats.drawCalls=meshes.length+surfaces.length;root.userData.stats=stats;root.userData.pickables=[...meshes,...surfaces];root.userData.dispose=()=>{for(const m of [...meshes,...surfaces])m.geometry.dispose();for(const m of Object.values(mats))m.dispose();root.removeFromParent();};return root;
}

/** Raycaster faceIndex is triangle-index into merged nonindexed geometry. */
export function getAirportHoverInfo(mesh,faceIndex){const u=mesh?.userData;if(u?.type!=='airport')return null;const v=faceIndex*3;const f=u.features?.find(f=>v>=f.start&&v<f.end);return {name:f?.name||u.name,kind:f?.kind||u.part,airportId:u.airportId,...(f?.heightM?{heightM:f.heightM}:{}),...(f?.osm?{osm:f.osm}:{})};}
